WFLY-16178 exclude SessionFactoryTestCase EntityTestCase due to NoSuchMethodError "java.io.Serializable org.hibernate.Session.save(java.lang.Object)" error
Signed-off-by: Scott Marlow <smarlow@redhat.com>