WFLY-2618 : Intermittent 'AssertionError: expected:<200> but was:<500>' in org.jboss.as.test.manualmode.ws.ReloadWSDLPublisherTestCase.testHelloStringAfterReload The test was failing intermittently because per default the JVM is using HttpConnection with keep-alive and a timeout of 5s. By setting the keep-alive to false in the setup and setting it to the value before the test on tear down we ensure a more stable test.