BZ-1034229 : Intermittent 'AssertionError: expected:<200> but was:<500>' Fixing test so that it doesn't use any keep-alive HttpConnection that makes it fails even if we close the connection